### ISSUE TITLE
1- issue 

### ISSUE THREAD

**Issue by wearnology** [wearnology/wearnology.github.io#1]
1-add links to contact page .

**Comment by wearnology** [comment]
2-Change from 'untitled document' to something relevant

**Comment by wearnology** [comment]
3-format links in the CSS main

**Comment by wearnology** [comment]
Add form spree link to contact page .

**Comment by jhawlc** [comment]
https://drive.google.com/file/d/1LdvnsQsw7Zz7w_Psw9cVSO8aoB878XEw/view?usp=drive_web&authuser=0
